<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Pembobotan_model extends CI_Model
{
    public function __construct()
    {
        parent::__construct();
        $this->load->model('Periode_model');

    }

    /*
     * Get pembobotan by idpembobotan
     */
    public function get_pembobotan($idpembobotan)
    {
        return $this->db->get_where('pembobotan', array('idpembobotan' => $idpembobotan))->row_array();
    }

    /*
     * Get all pembobotan
     */
    public function get_all_pembobotan()
    {
        $this->db->order_by('idpembobotan', 'desc');
        return $this->db->get('pembobotan')->result_array();
    }

    /*
     * function to add new pembobotan
     */
    public function add_pembobotan($params)
    {
        $this->db->insert('pembobotan', $params);
        return $this->db->insert_id();
    }

    /*
     * function to update pembobotan
     */
    public function update_pembobotan($idpembobotan, $params)
    {
        $this->db->where('idpembobotan', $idpembobotan);
        return $this->db->update('pembobotan', $params);
    }

    /*
     * function to delete pembobotan
     */
    public function delete_pembobotan($idpembobotan)
    {
        return $this->db->delete('pembobotan', array('idpembobotan' => $idpembobotan));
    }

    public function add_analisa($params)
    {
        $periode = $this->Periode_model->get_periodeaktif();
        $this->db->trans_begin();
        foreach ($params as $key => $nasabah) {
            $itemnasabah = [
                'idperiode' => $periode['idperiode'],
                'idnasabah' => $nasabah['idnasabah'],
            ];
            $this->db->insert('detailnasabah', $itemnasabah);
            foreach ($nasabah['value'] as $key => $value) {
                $item = [
                    'idnasabah' => $nasabah['idnasabah'],
                    'idperiode' => $periode['idperiode'],
                    'idkriteria' => $value['idkriteria'],
                    'subkriteria' => $value['subkriteria'],
                    'value' => $value['value'],
                    'nilai' => $value['nilai'],
                    'hasil' => $value['hasil'],
                    'idsubkriteria' => $value['idsubkriteria'],
                ];
                $this->db->insert('pembobotan', $item);
            }
        }
        if ($this->db->trans_status()) {
            $this->db->trans_commit();
            return true;
        } else {
            $this->db->trans_rollback();
            return false;
        }
    }
}
